name: MLOps CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t mlflow-tracking-server .

      - name: Push Docker image to registry
        run: |
          docker tag mlflow-tracking-server ghcr.io/yourusername/mlflow-tracking-server:latest
          docker push ghcr.io/yourusername/mlflow-tracking-server:latest
